"""review project update added reviews

Revision ID: 1ef8fe08209a
Revises: d6fdae8c951b
Create Date: 2023-06-14 12:58:58.857364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ef8fe08209a'
down_revision = 'd6fdae8c951b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('project_id', sa.Integer(), nullable=False))
    op.drop_constraint('review_project_fkey', 'review', type_='foreignkey')
    op.create_foreign_key(None, 'review', 'project', ['project_id'], ['id'])
    op.drop_column('review', 'project')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('project', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.create_foreign_key('review_project_fkey', 'review', 'project', ['project'], ['id'])
    op.drop_column('review', 'project_id')
    # ### end Alembic commands ###
