"""review update 

Revision ID: 2a9b7a279738
Revises: d0ace456b5db
Create Date: 2023-06-14 11:20:18.167761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a9b7a279738'
down_revision = 'd0ace456b5db'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('project', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review', 'project')
    # ### end Alembic commands ###
