"""update: project model, title, description column

Revision ID: a7c921080a2c
Revises: 0583b59dd9d9
Create Date: 2023-05-20 11:47:14.783184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7c921080a2c'
down_revision = '0583b59dd9d9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('title', sa.String(length=1000), nullable=True))
    op.add_column('project', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'description')
    op.drop_column('project', 'title')
    # ### end Alembic commands ###
