"""new contract

Revision ID: b5eb3e572436
Revises: 1ef8fe08209a
Create Date: 2023-07-11 12:54:40.742719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5eb3e572436'
down_revision = '1ef8fe08209a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract', sa.Column('contract_title', sa.String(length=200), nullable=True))
    op.drop_column('contract', 'message_id')
    op.drop_column('contract', 'conversation_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract', sa.Column('conversation_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('contract', sa.Column('message_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('contract', 'contract_title')
    # ### end Alembic commands ###
