"""companies model, address model, past companies

Revision ID: b7e1a2e1ab0c
Revises: a7c921080a2c
Create Date: 2023-05-29 16:37:19.788653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7e1a2e1ab0c'
down_revision = 'a7c921080a2c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.Column('logo_url', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=1000), nullable=True),
    sa.Column('city', sa.String(length=1000), nullable=True),
    sa.Column('street1', sa.String(length=1000), nullable=True),
    sa.Column('street2', sa.String(length=1000), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pastcompanies',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'company_id')
    )
    op.add_column('user', sa.Column('goopim_username', sa.String(length=200), nullable=True))
    op.create_unique_constraint(None, 'user', ['goopim_username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'goopim_username')
    op.drop_table('pastcompanies')
    op.drop_table('address')
    op.drop_table('companies')
    # ### end Alembic commands ###
