"""search log

Revision ID: cb37c92f10f1
Revises: b5eb3e572436
Create Date: 2023-08-05 00:46:15.585312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb37c92f10f1'
down_revision = 'b5eb3e572436'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('searchlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('creation_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contract', 'contract_title',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.drop_table('searchlog')
    # ### end Alembic commands ###
