"""review model

Revision ID: d0ace456b5db
Revises: 9e9add8a64c3
Create Date: 2023-06-14 11:04:07.203046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0ace456b5db'
down_revision = '9e9add8a64c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review', sa.String(length=500), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('review_owner', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('profile_cover_url', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile_cover_url')
    op.drop_table('review')
    # ### end Alembic commands ###
