"""review project update added reviews

Revision ID: d3d10629ef0b
Revises: 2a9b7a279738
Create Date: 2023-06-14 12:15:35.814615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3d10629ef0b'
down_revision = '2a9b7a279738'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
